### ISSUE TITLE
Music (new iTunes) support

### ISSUE THREAD

**Issue by arcovoltaico** [evan3334/node-itunes-library#1]
Hi there,
It's amazing the work you have done. I'd like to use it for retrieve some playlists from my Music library (the new iTunes version) without needing to export the XML library by hand. I assume you are not yet there, any plan about it? 
Thanks so much

**Comment by evstraw** [comment]
Hi,
I don't currently have any plans to support the new iTunes libraries. I made this package as kind of a one-off thing when I was exporting music from the iTunes library of a family member, and I don't really have any time (or access to Apple Music) to support it (nor do I even use Node.JS anymore, really). Sorry about that, I probably should have specified that I'm no longer supporting the project.

Edit: I've added a notice to state that I am not supporting the project in c6ed3d5dff9523643287a2548371081563d0772e.
